name: Post New Shiba
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      - run: npm run shibe
        env:
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
